import { DefaultActive } from "@/src/types/prospect/prospect.type";
export const ALL_COL: any = {
  "company": [
    { key: "id", label: "id", required: true },
    { key: "enquiry_id", label: "enquiry_id", required: false },
    { key: "fullName", label: "full_name", required: true },
    { key: "email", label: "email", required: false },
    { key: "phone", label: "phone", required: false },
    { key: "companyName", label: "company_name", required: false },
    { key: "designation", label: "designation", required: false },
    { key: "numberOfEmployees", label: "employees", required: false },
    { key: "industry", label: "industry", required: false },
    { key: "technologies", label: "technologies", required: false },
    { key: "keywords", label: "keywords", required: false },
    { key: "priority", label: "priority", required: false },
    { key: "projectType", label: "project_type", required: false },
    { key: "status", label: "status", required: false },
    { key: "isActive", label: "active", required: false },
    { key: "source", label: "source", required: false },
    { key: "message", label: "message", required: false },
    { key: "assignTo.firstName", label: "assign_to", required: false },

    // Location
    { key: "location.country", label: "country", required: false },
    { key: "location.state", label: "state", required: false },
    { key: "location.city", label: "city", required: false },
    { key: "location.zipcode", label: "zip_code", required: false },

    // Social Links
    { key: "socialLinks.linkedin", label: "linkedin", required: false },
    { key: "socialLinks.twitter", label: "twitter", required: false },
    { key: "socialLinks.github", label: "github", required: false },
    { key: "socialLinks.facebook", label: "facebook", required: false },
    { key: "socialLinks.instagram", label: "instagram", required: false },
    { key: "socialLinks.youtube", label: "youtube", required: false },
    { key: "socialLinks.website", label: "website", required: false },
    { key: "dataTags", label: "data_tags", required: false },
    { key: "createdAt", label: "created_at", required: true },
    { key: "createdBy", label: "created_by", required: true },
    { key: "actions", label: "actions", required: true },
  ],
  "people": [
    { key: "enquiry_id", label: "enquiry_id", required: false },
    { key: "fullName", label: "name", required: true },
    { key: "designation", label: "designation", required: false },
    { key: "companyName", label: "company", required: false },
    { key: "email", label: "email", required: false },
    { key: "phone", label: "phone", required: false },
    { key: "location", label: "location", required: false },
    { key: "linkedin", label: "linkedin", required: false },
    { key: "status", label: "status", required: false },
    { key: "dataTags", label: "data_tags", required: false },
    { key: "createdAt", label: "created_at", required: true },
    { key: "createdBy", label: "created_by", required: true },
    { key: "actions", label: "actions", required: true },
  ],
};

export const DEF_ACTIVE: DefaultActive = {
    "people": {
        enquiry_id: false,
        fullName: true,
        designation: true,
        companyName: true,
        email: true,
        phone: true,
        location: true,
        linkedin: true,
        status: true,
        dataTags: false,
        createdAt: true,
        "createdBy": true,
        actions: true,
    },
    company: {
        id: false,
        enquiry_id: false,
        fullName: true,
        email: true,
        phone: true,
        companyName: true,
        infoType: false,
        designation: true,

        numberOfEmployees: false,

        industry: false,
        technologies: false,
        keywords: false,

        priority: false,
        projectType: false,
        status: true,
        isActive: false,
        source: false,
        message: false,
        assignTo: false,

        "location.country": false,
        "location.state": false,
        "location.city": false,
        "location.zipcode": false,

        "socialLinks.linkedin": false,
        "socialLinks.twitter": false,
        "socialLinks.github": false,
        "socialLinks.facebook": false,
        "socialLinks.instagram": false,
        "socialLinks.youtube": false,
        "socialLinks.website": false,
        "socialLinks.other": false,
        "dataTags": false,
        deletedAt: false,
        createdAt: true,
        "createdBy": true,

        actions: true
    }

};