from app.core.enums import FORM_INPUT_TYPE, PRIORITY, SOURCE, PROJECT_TYPES, SALES_STATUS, COUNTRY_CODE, LANGUAGE_CODE, INDUSTRIES, EMPLOYEE_SENIORITY, FORM_FIELD_MODULES, DEAL_PIPELINE, DEAL_STAGES, DEAL_TYPE, FORECAST_CATEGORY


FORM_FIELDS = [
    {
        "name": "full name",
        "key": "fullName",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": True,
        "isActive": True,
        "placeholder": "Full Name",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "email",
        "key": "email",
        "type": FORM_INPUT_TYPE.EMAIL.value,
        "required": True,
        "isActive": True,
        "placeholder": "Email",
         "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "phone",
        "key": "phone",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": True,
        "isActive": True,
        "placeholder": "Phone",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "priority",
        "key": "priority",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
            {"label": PRIORITY.LOW.value, "value": PRIORITY.LOW.value }
            ,{"label": PRIORITY.MEDIUM.value, "value": PRIORITY.MEDIUM.value },
              {"label": PRIORITY.HIGH.value, "value": PRIORITY.HIGH.value }
              ],
        "required": True,
        "isActive": True,
        "placeholder": "Priority",
        "module": [FORM_FIELD_MODULES.LEAD.value, FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "source",
        "key": "source",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
            {"label": "Website", "value": SOURCE.WEBSITE.value},
        {"label": "Chatbot", "value": SOURCE.CHATBOT.value},
        {"label": "Email", "value": SOURCE.EMAIL.value},
        {"label": "Newsletter", "value": SOURCE.NEWSLETTER.value},

        {"label": "Call", "value": SOURCE.CALL.value},
        {"label": "WhatsApp", "value": SOURCE.WHATSAPP.value},
        {"label": "SMS", "value": SOURCE.SMS.value},
        {"label": "Walk In", "value": SOURCE.WALK_IN.value},

        {"label": "Ad", "value": SOURCE.AD.value},
        {"label": "Google Ads", "value": SOURCE.GOOGLE_ADS.value},
        {"label": "Facebook Ads", "value": SOURCE.FACEBOOK_ADS.value},
        {"label": "LinkedIn Ads", "value": SOURCE.LINKEDIN_ADS.value},
        {"label": "Instagram Ads", "value": SOURCE.INSTAGRAM_ADS.value},

        {"label": "Referral", "value": SOURCE.REFERRAL.value},
        {"label": "Partner", "value": SOURCE.PARTNER.value},
        {"label": "Affiliate", "value": SOURCE.AFFILIATE.value},
        {"label": "Reseller", "value": SOURCE.RESELLER.value},

        {"label": "Cold Call", "value": SOURCE.COLD_CALL.value},
        {"label": "Cold Email", "value": SOURCE.COLD_EMAIL.value},
        {"label": "LinkedIn Outreach", "value": SOURCE.LINKEDIN_OUTREACH.value},

        {"label": "Upwork", "value": SOURCE.UPWORK.value},
        {"label": "Fiverr", "value": SOURCE.FIVERR.value},
        {"label": "Freelancer", "value": SOURCE.FREELANCER.value},
        {"label": "Toptal", "value": SOURCE.TOPTAL.value},

        {"label": "Event", "value": SOURCE.EVENT.value},
        {"label": "Conference", "value": SOURCE.CONFERENCE.value},
        {"label": "Meetup", "value": SOURCE.MEETUP.value},
        {"label": "Exhibition", "value": SOURCE.EXHIBITION.value},

        {"label": "Other", "value": SOURCE.OTHER.value},
        ],
        "required": True,
        "isActive": True,
        "placeholder": "Source",
         "module": [FORM_FIELD_MODULES.LEAD.value, FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "project type",
        "key": "projectType",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [

        
        {"label": "Mobile App", "value": PROJECT_TYPES.MOBILE_APP.value},
        {"label": "Website", "value": PROJECT_TYPES.WEBSITE.value},
        {"label": "Web App", "value": PROJECT_TYPES.WEB_APP.value},
        {"label": "CRM", "value": PROJECT_TYPES.CRM.value},
        {"label": "ERP", "value": PROJECT_TYPES.ERP.value},
        {"label": "Custom Software", "value": PROJECT_TYPES.CUSTOM_SOFTWARE.value},


        {"label": "AI / ML", "value": PROJECT_TYPES.AI_ML.value},
        {"label": "Data Science", "value": PROJECT_TYPES.DATA_SCIENCE.value},
        {"label": "Blockchain", "value": PROJECT_TYPES.BLOCKCHAIN.value},
        {"label": "IoT", "value": PROJECT_TYPES.IOT.value},

        {"label": "UI / UX Design", "value": PROJECT_TYPES.UI_UX_DESIGN.value},
        {"label": "Graphic Design", "value": PROJECT_TYPES.GRAPHIC_DESIGN.value},
        {"label": "Branding", "value": PROJECT_TYPES.BRANDING.value},

        {"label": "Digital Marketing", "value": PROJECT_TYPES.DIGITAL_MARKETING.value},
        {"label": "SEO", "value": PROJECT_TYPES.SEO.value},
        {"label": "Social Media Marketing", "value": PROJECT_TYPES.SOCIAL_MEDIA_MARKETING.value},
        {"label": "Content Marketing", "value": PROJECT_TYPES.CONTENT_MARKETING.value},

        {"label": "Testing", "value": PROJECT_TYPES.TESTING.value},
        {"label": "QA Automation", "value": PROJECT_TYPES.QA_AUTOMATION.value},
        {"label": "Maintenance & Support", "value": PROJECT_TYPES.MAINTENANCE_SUPPORT.value},

        {"label": "Cloud Services", "value": PROJECT_TYPES.CLOUD_SERVICES.value},
        {"label": "DevOps", "value": PROJECT_TYPES.DEVOPS.value},
        {"label": "Cyber Security", "value": PROJECT_TYPES.CYBER_SECURITY.value},

        {"label": "E-commerce", "value": PROJECT_TYPES.ECOMMERCE.value},
        {"label": "CMS", "value": PROJECT_TYPES.CMS.value},

        {"label": "IT Consulting", "value": PROJECT_TYPES.IT_CONSULTING.value},
        {"label": "Product Consulting", "value": PROJECT_TYPES.PRODUCT_CONSULTING.value}
    
        ],
        "required": True,
        "isActive": True,
        "placeholder": "Project Type",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },

    {
        "name": "sales status",
        "key": "status",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
            {"label": "New", "value": SALES_STATUS.NEW.value},
            {"label": "Proposal", "value": SALES_STATUS.PROPOSAL.value},
            {"label": "Qualified", "value": SALES_STATUS.QUALIFIED.value},
            {"label": "Contacted", "value": SALES_STATUS.CONTACTED.value},
            {"label": "Won", "value": SALES_STATUS.WON.value},
            {"label": "Lost", "value": SALES_STATUS.LOST.value},
        ],
        "required": False,
        "isActive": True,
        "placeholder": "Sales Status",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "company name",
        "key": "companyName",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": True,
        "isActive": True,
        "placeholder": "Company Name",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "city",
        "key": "city",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": False,
        "isActive": True,
        "placeholder": "City",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "country",
        "key": "country",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
        {"label": "Afghanistan", "value": "AF"},
        {"label": "Aland Islands", "value": "AX"},
        {"label": "Albania", "value": "AL"},
        {"label": "Algeria", "value": "DZ"},
        {"label": "American Samoa", "value": "AS"},
        {"label": "Andorra", "value": "AD"},
        {"label": "Angola", "value": "AO"},
        {"label": "Anguilla", "value": "AI"},
        {"label": "Antarctica", "value": "AQ"},
        {"label": "Antigua And Barbuda", "value": "AG"},
        {"label": "Argentina", "value": "AR"},
        {"label": "Armenia", "value": "AM"},
        {"label": "Aruba", "value": "AW"},
        {"label": "Australia", "value": "AU"},
        {"label": "Austria", "value": "AT"},
        {"label": "Azerbaijan", "value": "AZ"},
        {"label": "Bahamas", "value": "BS"},
        {"label": "Bahrain", "value": "BH"},
        {"label": "Bangladesh", "value": "BD"},
        {"label": "Barbados", "value": "BB"},
        {"label": "Belarus", "value": "BY"},
        {"label": "Belgium", "value": "BE"},
        {"label": "Belize", "value": "BZ"},
        {"label": "Benin", "value": "BJ"},
        {"label": "Bermuda", "value": "BM"},
        {"label": "Bhutan", "value": "BT"},
        {"label": "Bolivia", "value": "BO"},
        {"label": "Bosnia And Herzegovina", "value": "BA"},
        {"label": "Botswana", "value": "BW"},
        {"label": "Brazil", "value": "BR"},
        {"label": "Brunei", "value": "BN"},
        {"label": "Bulgaria", "value": "BG"},
        {"label": "Burkina Faso", "value": "BF"},
        {"label": "Burundi", "value": "BI"},
        {"label": "Cambodia", "value": "KH"},
        {"label": "Cameroon", "value": "CM"},
        {"label": "Canada", "value": "CA"},
        {"label": "Cape Verde", "value": "CV"},
        {"label": "Cayman Islands", "value": "KY"},
        {"label": "Central African Republic", "value": "CF"},
        {"label": "Chad", "value": "TD"},
        {"label": "Chile", "value": "CL"},
        {"label": "China", "value": "CN"},
        {"label": "Colombia", "value": "CO"},
        {"label": "Costa Rica", "value": "CR"},
        {"label": "Croatia", "value": "HR"},
        {"label": "Cuba", "value": "CU"},
        {"label": "Cyprus", "value": "CY"},
        {"label": "Czech Republic", "value": "CZ"},
        {"label": "Denmark", "value": "DK"},
        {"label": "Dominican Republic", "value": "DO"},
        {"label": "Ecuador", "value": "EC"},
        {"label": "Egypt", "value": "EG"},
        {"label": "El Salvador", "value": "SV"},
        {"label": "Estonia", "value": "EE"},
        {"label": "Ethiopia", "value": "ET"},
        {"label": "Finland", "value": "FI"},
        {"label": "France", "value": "FR"},
        {"label": "Germany", "value": "DE"},
        {"label": "Ghana", "value": "GH"},
        {"label": "Greece", "value": "GR"},
        {"label": "Hong Kong", "value": "HK"},
        {"label": "Hungary", "value": "HU"},
        {"label": "Iceland", "value": "IS"},
        {"label": "India", "value": "IN"},
        {"label": "Indonesia", "value": "ID"},
        {"label": "Iran", "value": "IR"},
        {"label": "Iraq", "value": "IQ"},
        {"label": "Ireland", "value": "IE"},
        {"label": "Israel", "value": "IL"},
        {"label": "Italy", "value": "IT"},
        {"label": "Japan", "value": "JP"},
        {"label": "Kenya", "value": "KE"},
        {"label": "Kuwait", "value": "KW"},
        {"label": "Malaysia", "value": "MY"},
        {"label": "Maldives", "value": "MV"},
        {"label": "Mexico", "value": "MX"},
        {"label": "Netherlands", "value": "NL"},
        {"label": "New Zealand", "value": "NZ"},
        {"label": "Nigeria", "value": "NG"},
        {"label": "Norway", "value": "NO"},
        {"label": "Pakistan", "value": "PK"},
        {"label": "Philippines", "value": "PH"},
        {"label": "Poland", "value": "PL"},
        {"label": "Portugal", "value": "PT"},
        {"label": "Qatar", "value": "QA"},
        {"label": "Romania", "value": "RO"},
        {"label": "Russia", "value": "RU"},
        {"label": "Saudi Arabia", "value": "SA"},
        {"label": "Singapore", "value": "SG"},
        {"label": "South Africa", "value": "ZA"},
        {"label": "South Korea", "value": "KR"},
        {"label": "Spain", "value": "ES"},
        {"label": "Sri Lanka", "value": "LK"},
        {"label": "Sweden", "value": "SE"},
        {"label": "Switzerland", "value": "CH"},
        {"label": "Taiwan", "value": "TW"},
        {"label": "Thailand", "value": "TH"},
        {"label": "Turkey", "value": "TR"},
        {"label": "Ukraine", "value": "UA"},
        {"label": "United Arab Emirates", "value": "AE"},
        {"label": "United Kingdom", "value": "GB"},
        {"label": "United States", "value": "US"},
        {"label": "Vietnam", "value": "VN"},
        {"label": "Zimbabwe", "value": "ZW"}
    ],
        "required": False,
        "isActive": True,
        "placeholder": "COUNTRY",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {"name": "postal code",
        "key": "postalCode",
        "type": FORM_INPUT_TYPE.NUMBER.value,
        "required": False,
        "isActive": True,
        "placeholder": "Postal Code",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {"name": "Language",
        "key": "language",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "required": False,
        "options": [
       
        {"label": "English", "value": LANGUAGE_CODE.ENGLISH.value},
        {"label": "Spanish", "value": LANGUAGE_CODE.SPANISH.value},
        {"label": "French", "value": LANGUAGE_CODE.FRENCH.value},
        {"label": "German", "value": LANGUAGE_CODE.GERMAN.value},
        {"label": "Italian", "value": LANGUAGE_CODE.ITALIAN.value},
        {"label": "Portuguese", "value": LANGUAGE_CODE.PORTUGUESE.value},
        {"label": "Dutch", "value": LANGUAGE_CODE.DUTCH.value},
        {"label": "Russian", "value": LANGUAGE_CODE.RUSSIAN.value},
        {"label": "Ukrainian", "value": LANGUAGE_CODE.UKRAINIAN.value},
        {"label": "Polish", "value": LANGUAGE_CODE.POLISH.value},
        {"label": "Czech", "value": LANGUAGE_CODE.CZECH.value},
        {"label": "Slovak", "value": LANGUAGE_CODE.SLOVAK.value},
        {"label": "Hungarian", "value": LANGUAGE_CODE.HUNGARIAN.value},
        {"label": "Romanian", "value": LANGUAGE_CODE.ROMANIAN.value},
        {"label": "Bulgarian", "value": LANGUAGE_CODE.BULGARIAN.value},
        {"label": "Greek", "value": LANGUAGE_CODE.GREEK.value},
        {"label": "Turkish", "value": LANGUAGE_CODE.TURKISH.value},
        {"label": "Arabic", "value": LANGUAGE_CODE.ARABIC.value},
        {"label": "Hebrew", "value": LANGUAGE_CODE.HEBREW.value},
        {"label": "Persian", "value": LANGUAGE_CODE.PERSIAN.value},
        {"label": "Urdu", "value": LANGUAGE_CODE.URDU.value},
        {"label": "Hindi", "value": LANGUAGE_CODE.HINDI.value},
        {"label": "Bengali", "value": LANGUAGE_CODE.BENGALI.value},
        {"label": "Tamil", "value": LANGUAGE_CODE.TAMIL.value},
        {"label": "Telugu", "value": LANGUAGE_CODE.TELUGU.value},
        {"label": "Marathi", "value": LANGUAGE_CODE.MARATHI.value},
        {"label": "Gujarati", "value": LANGUAGE_CODE.GUJARATI.value},
        {"label": "Kannada", "value": LANGUAGE_CODE.KANNADA.value},
        {"label": "Malayalam", "value": LANGUAGE_CODE.MALAYALAM.value},
        {"label": "Punjabi", "value": LANGUAGE_CODE.PUNJABI.value},
        {"label": "Chinese (Simplified)", "value": LANGUAGE_CODE.CHINESE_SIMPLIFIED.value},
        {"label": "Japanese", "value": LANGUAGE_CODE.JAPANESE.value},
        {"label": "Korean", "value": LANGUAGE_CODE.KOREAN.value},
        {"label": "Thai", "value": LANGUAGE_CODE.THAI.value},
        {"label": "Vietnamese", "value": LANGUAGE_CODE.VIETNAMESE.value},
        {"label": "Indonesian", "value": LANGUAGE_CODE.INDONESIAN.value},
        {"label": "Malay", "value": LANGUAGE_CODE.MALAY.value},
        {"label": "Filipino", "value": LANGUAGE_CODE.FILIPINO.value},
        {"label": "Swedish", "value": LANGUAGE_CODE.SWEDISH.value},
        {"label": "Norwegian", "value": LANGUAGE_CODE.NORWEGIAN.value},
        {"label": "Danish", "value": LANGUAGE_CODE.DANISH.value},
        {"label": "Finnish", "value": LANGUAGE_CODE.FINNISH.value},
        {"label": "Icelandic", "value": LANGUAGE_CODE.ICELANDIC.value},
        {"label": "Afrikaans", "value": LANGUAGE_CODE.AFRIKAANS.value},
        {"label": "Swahili", "value": LANGUAGE_CODE.SWAHILI.value},
        {"label": "Zulu", "value": LANGUAGE_CODE.ZULU.value},
        {"label": "Latin", "value": LANGUAGE_CODE.LATIN.value},
        ],
        "isActive": True,
        "placeholder": "Language",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    }, 
    {
        "name": "industry",
        "key": "industry",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "required": False,
        "options": [
            {"label": "Technology", "value": INDUSTRIES.TECHNOLOGIES.value},
        {"label": "Healthcare", "value": INDUSTRIES.HEALTHCARE.value},
        {"label": "Finance", "value": INDUSTRIES.FINANCE.value},
        {"label": "Education", "value": INDUSTRIES.EDUCATION.value},
        {"label": "Manufacturing", "value": INDUSTRIES.MANUFACTURING.value},
        {"label": "Retail", "value": INDUSTRIES.RETAIL.value},
        {"label": "Consulting", "value": INDUSTRIES.CONSULTING.value},
        {"label": "Real Estate", "value": INDUSTRIES.REALESTATE.value},
        {"label": "Other", "value": INDUSTRIES.OTHER.value},
              ],
        "isActive": True,
        "placeholder": "Industry",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "employee role",
        "key": "employeeRole",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": False,
        "isActive": True,
        "placeholder": "Employee Role",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "employee seniority",
        "key": "employeeSeniority",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
           {"label": "Entry Level", "value": EMPLOYEE_SENIORITY.ENTRY_LEVEL.value},
        {"label": "Mid Level", "value": EMPLOYEE_SENIORITY.MID_LEVEL.value},
        {"label": "Senior Level", "value": EMPLOYEE_SENIORITY.SENIOR_LEVEL.value},
        {"label": "Lead", "value": EMPLOYEE_SENIORITY.LEAD.value},
        {"label": "Manager", "value": EMPLOYEE_SENIORITY.MANAGER.value},
        {"label": "Director", "value": EMPLOYEE_SENIORITY.DIRECTOR.value},
        {"label": "Vice President (VP)", "value": EMPLOYEE_SENIORITY.VP.value},
        {"label": "C-Level", "value": EMPLOYEE_SENIORITY.C_LEVEL.value},
        {"label": "Owner / Founder", "value": EMPLOYEE_SENIORITY.OWNER.value},
        ],
        "required": False,
        "isActive": True,
        "placeholder": "Employee Seniority",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "Message",
        "key": "message",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": False,
        "isActive": True,
        "placeholder": "Message",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },
    {
        "name": "membership notes",
        "key": "membershipNotes",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": False,
        "isActive": True,
        "placeholder": "Membership Notes",
        "module": [FORM_FIELD_MODULES.LEAD.value]
    },

    #<<<<<<<<<<<<<<<<------------------ DEAL ---------------->>>>>>>>>>>>>>>

    {
        "name": "deal name",
        "key": "dealName",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": True,
        "isActive": True,
        "placeholder": "Deal Name",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "deal pipeline",
        "key": "dealPipeline",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
           {"label": "qualification", "value": DEAL_PIPELINE.QUALIFICATION.value},
        {"label": "requirement analysis", "value": DEAL_PIPELINE.REQUIREMENT_ANALYSIS.value},
        {"label": "proposal", "value": DEAL_PIPELINE.PROPOSAL.value},
        {"label": "negotiation", "value": DEAL_PIPELINE.NEGOTIATION.value},
        {"label": "won", "value": DEAL_PIPELINE.WON.value},
        {"label": "lost", "value": DEAL_PIPELINE.LOST.value},
        ],
        "required": True,
        "isActive": True,
        "placeholder": "Deal Pipeline",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "deal stage",
        "key": "dealStage",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
           {"label": "qualification", "value": DEAL_STAGES.QUALIFICATION.value},
        {"label": "requirement analysis", "value": DEAL_STAGES.REQUIREMENT_ANALYSIS.value},
        {"label": "proposal", "value": DEAL_STAGES.PROPOSAL.value},
        {"label": "negotiation", "value": DEAL_STAGES.NEGOTIATION.value},
        {"label": "won", "value": DEAL_STAGES.WON.value},
        {"label": "lost", "value": DEAL_STAGES.LOST.value},


        ],
        "required": True,
        "isActive": True,
        "placeholder": "Deal Pipeline",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "deal owner",
        "key": "dealOwner",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": True,
        "isActive": True,
        "placeholder": "Deal Owner",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "deal type",
        "key": "dealType",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
           {"label": "new business", "value": DEAL_TYPE.NEW_BUSINESS.value},
        {"label": "existing business", "value": DEAL_TYPE.EXISTING_BUSINESS.value},
        {"label": "partnership", "value": DEAL_TYPE.PARTNERSHIP.value},
        {"label": "other", "value": DEAL_TYPE.OTHER.value},



        ],
        "required": True,
        "isActive": True,
        "placeholder": "Deal Type",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "close date",
        "key": "closeDate",
        "type": FORM_INPUT_TYPE.DATE.value,
        "required": True,
        "isActive": True,
        "placeholder": "Close Date",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "create date",
        "key": "createDate",
        "type": FORM_INPUT_TYPE.DATE.value,
        "required": True,
        "isActive": True,
        "placeholder": "Create Date",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "amount",
        "key": "amount",
        "type": FORM_INPUT_TYPE.NUMBER.value,
        "required": True,
        "isActive": True,
        "placeholder": "Amount",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "deal collaborator",
        "key": "dealCollaborator",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": True,
        "isActive": True,
        "placeholder": "Deal Collaborator",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "deal description",
        "key": "dealDescription",
        "type": FORM_INPUT_TYPE.TEXTAREA.value,
        "required": True,
        "isActive": True,
        "placeholder": "Deal Description",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "deal probability",
        "key": "dealProbability",
        "type": FORM_INPUT_TYPE.NUMBER.value,
        "required": True,
        "isActive": True,
        "placeholder": "Deal Probability",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "forecast probability",
        "key": "forecastProbability",
        "type": FORM_INPUT_TYPE.NUMBER.value,
        "required": True,
        "isActive": True,
        "placeholder": "Forecast Probability",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "next step",
        "key": "nextStep",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": True,
        "isActive": True,
        "placeholder": "Next Step",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "forecast category",
        "key": "forecastCategory",
        "type": FORM_INPUT_TYPE.SELECT.value,
        "options": [
            {"label": "pipeline", "value": FORECAST_CATEGORY.PIPELINE.value},
            {"label": "best case", "value": FORECAST_CATEGORY.BEST_CASE.value},
            {"label": "commit", "value": FORECAST_CATEGORY.COMMIT.value},
            {"label": "closed", "value": FORECAST_CATEGORY.CLOSED.value},
        ],
        "required": True,
        "isActive": True,
        "placeholder": "Forecast Category",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "closed won reason",
        "key": "closedWonReason",
        "type": FORM_INPUT_TYPE.TEXTAREA.value,
        "required": True,
        "isActive": True,
        "placeholder": "Closed Won Reason",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "closed lost reason",
        "key": "closedLostReason",
        "type": FORM_INPUT_TYPE.TEXTAREA.value,
        "required": True,
        "isActive": True,
        "placeholder": "Closed Lost Reason",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },
    {
        "name": "original traffic source",
        "key": "originalTrafficSource",
        "type": FORM_INPUT_TYPE.TEXT.value,
        "required": True,
        "isActive": True,
        "placeholder": "Original Traffic Source",
        "module": [FORM_FIELD_MODULES.DEAL.value]
    },




]
