PERMISSIONS = [
    # users
    {
        "code": "user:create",
        "module": "user",
        "action": "create",
        "title": "create user",
        "description": "Permission for creating a user",
    },
    {
        "code": "user:read",
        "module": "user",
        "action": "read",
        "title": "read user",
        "description": "permission for See the user data",
    },
    {
        "code": "user:update",
        "module": "user",
        "action": "update",
        "title": "update user",
        "description": "permission for update user data",
    },
    {
        "code": "user:delete",
        "module": "user",
        "action": "delete",
        "title": "delete user",
        "description": "permission for delete user data",
    },
    # ROLES
    {
        "code": "role:create",
        "module": "role",
        "action": "create",
        "title": "create role",
        "description": "Permission for creating a role",
    },
    {
        "code": "role:read",
        "module": "role",
        "action": "read",
        "title": "read role",
        "description": "Permission for read a role",
    },
    {
        "code": "role:update",
        "module": "role",
        "action": "update",
        "title": "update role",
        "description": "Permission for update a role",
    },
    {
        "code": "role:delete",
        "module": "role",
        "action": "delete",
        "title": "delete role",
        "description": "Permission for delete a role",
    },
    # ENQUIRY
    {
        "code": "enquiry:create",
        "module": "enquiry",
        "action": "create",
        "title": "create enquiry",
        "description": "permission for create enquiry data",
    },
    {
        "code": "enquiry:read",
        "module": "enquiry",
        "action": "read",
        "title": "read enquiry",
        "description": "permission for read enquiry data",
    },
    {
        "code": "enquiry:update",
        "module": "enquiry",
        "action": "update",
        "title": "update enquiry",
        "description": "permission for update enquiry data",
    },
    {
        "code": "enquiry:assign",
        "module": "enquiry",
        "action": "update",
        "title": "assign enquiry",
        "description": "permission for assign enquiry data",
    },
    {
        "code": "enquiry:delete",
        "module": "enquiry",
        "action": "delete",
        "title": "delete enquiry",
        "description": "permission for delete enquiry data",
    },
    {
        "code": "lead:create",
        "module": "lead",
        "action": "create",
        "title": "create lead",
        "description": "permission for create lead data",
    },
    {
        "code": "lead:read",
        "module": "lead",
        "action": "read",
        "title": "read lead",
        "description": "permission for read lead data",
    },
    {
        "code": "lead:update",
        "module": "lead",
        "action": "update",
        "title": "update lead",
        "description": "permission for update lead data",
    },
    {
        "code": "lead:assign",
        "module": "lead",
        "action": "update",
        "title": "assign lead",
        "description": "permission for assign lead data",
    },
    {
        "code": "lead:reassign",
        "module": "lead",
        "action": "update",
        "title": "reassign lead",
        "description": "permission for reassign lead data",
    },
    {
        "code": "lead:assignView",
        "module": "lead",
        "action": "read",
        "title": "view assign lead information",
        "description": "permission for view assign lead data",
    },

    {
        "code": "lead:delete",
        "module": "lead",
        "action": "delete",
        "title": "delete lead",
        "description": "permission for delete lead data",
    },
    {
        "code": "team:create",
        "module": "team",
        "action": "create",
        "title": "create team",
        "description": "permission for create team data",
    },
    {
        "code": "team:read",
        "module": "team",
        "action": "read",
        "title": "read team",
        "description": "permission for read team data",
    },
    {
        "code": "team:update",
        "module": "team",
        "action": "update",
        "title": "update team",
        "description": "permission for update team data",
    },
    {
        "code": "team:delete",
        "module": "team",
        "action": "delete",
        "title": "delete team",
        "description": "permission for delete team data",
    },
    {
        "code": "team_cat:create",
        "module": "team_cat",
        "action": "create",
        "title": "create team category",
        "description": "permission for create team category data",
    },
    {
        "code": "team_cat:read",
        "module": "team_cat",
        "action": "read",
        "title": "read team category",
        "description": "permission for read team category data",
    },
    {
        "code": "team_cat:update",
        "module": "team_cat",
        "action": "update",
        "title": "update team category",
        "description": "permission for update team category data",
    },
    {
        "code": "team_cat:delete",
        "module": "team_cat",
        "action": "delete",
        "title": "delete team category",
        "description": "permission for delete team category data",
    },
    {
        "code": "deal:create",
        "module": "deal",
        "action": "create",
        "title": "create deal",
        "description": "permission for create deal data",
    },
    {
        "code": "deal:read",
        "module": "deal",
        "action": "read",
        "title": "read deal",
        "description": "permission for read deal data",
    },
    {
        "code": "deal:update",
        "module": "deal",
        "action": "update",
        "title": "update deal",
        "description": "permission for update deal data",
    },
    {
        "code": "deal:delete",
        "module": "deal",
        "action": "delete",
        "title": "delete deal",
        "description": "permission for delete deal data",
    },
    {
        "code": "quote:create",
        "module": "quote",
        "action": "create",
        "title": "create quote",
        "description": "permission for create quote data",
    },
    {
        "code": "quote:read",
        "module": "quote",
        "action": "read",
        "title": "read quote",
        "description": "permission for read quote data",
    },
    {
        "code": "quote:update",
        "module": "quote",
        "action": "update",
        "title": "update quote",
        "description": "permission for update quote data",
    },
    {
        "code": "quote:delete",
        "module": "quote",
        "action": "delete",
        "title": "delete quote",
        "description": "permission for delete quote data",
    },
    {
        "code": "event:create",
        "module": "event",
        "action": "create",
        "title": "create event",
        "description": "permission for create event data",
    },
    {
        "code": "event:read",
        "module": "event",
        "action": "read",
        "title": "read event",
        "description": "permission for read event data",
    },
    {
        "code": "event:update",
        "module": "event",
        "action": "update",
        "title": "update event",
        "description": "permission for update event data",
    },
    {
        "code": "event:delete",
        "module": "event",
        "action": "delete",
        "title": "delete event",
        "description": "permission for delete event data",
    },
    {
        "code": "event:create",
        "module": "event",
        "action": "create",
        "title": "create event",
        "description": "permission for create event data",
    },
    {
        "code": "invoice:read",
        "module": "invoice",
        "action": "read",
        "title": "read invoice",
        "description": "permission for read invoice data",
    },
    {
        "code": "invoice:update",
        "module": "invoice",
        "action": "update",
        "title": "update invoice",
        "description": "permission for update invoice data (allowed fields only)",
    },
    {
        "code": "invoice:delete",
        "module": "invoice",
        "action": "delete",
        "title": "delete invoice",
        "description": "permission for delete or void invoice",
    },
    {
        "code": "invoice:send",
        "module": "invoice",
        "action": "send",
        "title": "send invoice",
        "description": "permission for send invoice to client",
    },
    {
        "code": "invoice:download",
        "module": "invoice",
        "action": "download",
        "title": "download invoice",
        "description": "permission for download invoice PDF",
    },
    {
        "code": "invoice:mark-paid",
        "module": "invoice",
        "action": "mark-paid",
        "title": "mark invoice as paid",
        "description": "permission for mark invoice payment status as paid",
    },
    {
    "code": "invoice:cancel",
    "module": "invoice",
    "action": "cancel",
    "title": "cancel invoice",
    "description": "permission for cancel invoice without deleting it"
},
{
        "code": "note:create",
        "module": "note",
        "action": "create",
        "title": "create note",
        "description": "permission for create note data",
    },
    {
        "code": "note:read",
        "module": "note",
        "action": "read",
        "title": "read note",
        "description": "permission for read note data",
    },
    {
        "code": "note:update",
        "module": "note",
        "action": "update",
        "title": "update note",
        "description": "permission for update note data",
    },
    {
        "code": "note:delete",
        "module": "note",
        "action": "delete",
        "title": "delete note",
        "description": "permission for delete note data",
    },
     {
        "code": "prospect:create",
        "module": "prospect",
        "action": "create",
        "title": "create prospect",
        "description": "permission for create prospect data",
    },
    {
        "code": "prospect:read",
        "module": "prospect",
        "action": "read",
        "title": "read prospect",
        "description": "permission for read prospect data",
    },
    {
        "code": "prospect:update",
        "module": "prospect",
        "action": "update",
        "title": "update prospect",
        "description": "permission for update prospect data",
    },
    {
        "code": "prospect:delete",
        "module": "prospect",
        "action": "delete",
        "title": "delete prospect",
        "description": "permission for delete prospect data",
    },
    {
        "code": "telephone:create",
        "module": "telephone",
        "action": "create",
        "title": "create telephone",
        "description": "permission for create telephone number"
    },
    {
        "code": "telephone:assign",
        "module": "telephone",
        "action": "assign",
        "title": "assign telephone",
        "description": "permission for assign telephone number"
    },
    {
        "code": "telephone:read",
        "module": "telephone",
        "action": "read",
        "title": "read telephone",
        "description": "permission for read telephone number"
    },
    {
        "code": "telephone:update",
        "module": "telephone",
        "action": "update",
        "title": "update telephone",
        "description": "permission for update telephone number"
    },
    {
        "code": "telephone:delete",
        "module": "telephone",
        "action": "delete",
        "title": "delete telephone",
        "description": "permission for delete telephone number"
    }, 
    {
        "code": "emailTemplate:create",
        "module": "emailTemplate",
        "action": "create",
        "title": "create emailTemplate",
        "description": "permission for create email template "
    },
    {
         "code": "emailTemplate:read",
        "module": "emailTemplate",
        "action": "read",
        "title": "read emailTemplate",
        "description": "permission for read email template "
    },
    {
         "code": "emailTemplate:update",
        "module": "emailTemplate",
        "action": "update",
        "title": "update emailTemplate",
        "description": "permission for update email template "
    },
    {
         "code": "emailTemplate:delete",
        "module": "emailTemplate",
        "action": "delete",
        "title": "delete emailTemplate",
        "description": "permission for delete email template "
    },
    {
        "code": "sms:send",
        "module": "sms",
        "action": "send",
        "title": "send sms",
       "description": "permission for send sms "
    },
    {
        "code": "sms:read",
        "module": "sms",
        "action": "read",
        "title": "read sms",
       "description": "permission for read sms "
    },
    {
        "code": "sms:delete",
        "module": "sms",
        "action": "delete",
        "title": "delete sms",
       "description": "permission for delete sms "
    },
    {
        "code": "sms:viewlog",
        "module": "sms",
        "action": "viewlog",
        "title": "view sms log",
       "description": "permission for view sms log "
    },
    {
        "code": "email:send",
        "module": "email",
        "action": "send",
        "title": "send email",
       "description": "permission for send email "
    },
    {
        "code": "email:read",
        "module": "email",
        "action": "read",
        "title": "read email",
       "description": "permission for read email "
    },
    
    {
        "code": "email:delete",
        "module": "email",
        "action": "delete",
        "title": "delete email",
       "description": "permission for delete email"
    },
    {
        "code": "call:call",
        "module": "call",
        "action": "call",
        "title": "call",
       "description": "permission for call"
    },
    {
       "code": "dashboard:read",
        "module": "dashboard",
        "action": "read",
        "title": "read dashboard",
       "description": "permission for view dashboard" 
    },
    {
        "code": "task:create",
        "module": "task",
        "action": "create",
        "title": "create task",
        "description": "permission for create task data",
    },
    {
        "code": "task:read",
        "module": "task",
        "action": "read",
        "title": "read task",
        "description": "permission for read task data",
    },
    {
        "code": "task:update",
        "module": "task",
        "action": "update",
        "title": "update task",
        "description": "permission for update task data",
    },
    {
        "code": "task:delete",
        "module": "task",
        "action": "delete",
        "title": "delete task",
        "description": "permission for delete task data",
    },
    {
        "code": "task:assign",
        "module": "task",
        "action": "assign",
        "title": "assign task",
        "description": "permission for assign task data",
    },
    {
        "code": "task:statusChange",
        "module": "task",
        "action": "Update",
        "title": "change task status",
        "description": "permission for change task status data",

    },
    {
        "code": "task:markStatusComplete",
        "module": "task",
        "action": "Update",
        "title": "Mark status complete",
        "description": "permission for mark status to complete",

    },
    
    {
        "code": "taskCategory:create",
        "module": "taskCategory",
        "action": "create",
        "title": "create task category",
        "description": "permission for create task category data",
    },
    {
        "code": "taskCategory:read",
        "module": "taskCategory",
        "action": "read",
        "title": "read task category",
        "description": "permission for read task category data",
    },
    {
        "code": "taskCategory:update",
        "module": "taskCategory",
        "action": "update",
        "title": "update task category",
        "description": "permission for update task category data",
    },
    {
        "code": "taskCategory:delete",
        "module": "taskCategory",
        "action": "delete",
        "title": "delete task category",
        "description": "permission for delete task category data",
    },
    {
        "code": "taskStatus:create",
        "module": "taskStatus",
        "action": "create",
        "title": "create task status",
        "description": "permission for create task status data",
    },
    {
        "code": "taskStatus:read",
        "module": "taskStatus",
        "action": "read",
        "title": "read task status",
        "description": "permission for read task status data",
    },
    {
        "code": "taskStatus:update",
        "module": "taskStatus",
        "action": "update",
        "title": "update task status",
        "description": "permission for update task status data",
    },
    {
        "code": "taskStatus:delete",
        "module": "taskStatus",
        "action": "delete",
        "title": "delete task status",
        "description": "permission for delete task status data",
    },
    {
        "code": "otp:read",
        "module": "otp",
        "action": "read",
        "title": "read otp",
        "description": "permission for read otp",
    },
    {
        "code": "remark:read",
        "module": "remark",
        "action": "read",
        "title": "read remark",
        "description": "permission for read remark",
    },
    {
        "code": "remark:create",
        "module": "remark",
        "action": "create",
        "title": "create remark",
        "description": "permission for create remark",
    },
    {
        "code": "remark:update",
        "module": "remark",
        "action": "update",
        "title": "update remark",
        "description": "permission for update remark",
    },
    {
        "code": "remark:delete",
        "module": "remark",
        "action": "delete",
        "title": "delete remark",
        "description": "permission for delete remark",
    },
    {
        "code": "taskReport:create",
        "module": "taskReport",
        "action": "create",
        "title": "create taskReport",
        "description": "permission for create task report",
    },
    {
        "code": "taskReport:read",
        "module": "taskReport",
        "action": "read",
        "title": "read taskReport",
        "description": "permission for read task report",
    },
    {
        "code": "taskReport:update",
        "module": "taskReport",
        "action": "update",
        "title": "update taskReport",
        "description": "permission for update task report",
    },
    {
        "code": "taskReport:delete",
        "module": "taskReport",
        "action": "delete",
        "title": "delete taskReport",
        "description": "permission for delete task report",
    },
    {
        "code": "task_timer:read",
        "module": "taskTimer",
        "action": "read",
        "title": "read task timer",
        "description": "permission for read task timer report",
    },
    {
        "code": "task_timer:start",
        "module": "taskTimer",
        "action": "start",
        "title": "start task timer",
        "description": "permission for start task timer",
    },
    {
        "code": "task_timer:pause",
        "module": "taskTimer",
        "action": "pause",
        "title": "pause task timer",
        "description": "permission for pause task timer",
    },
    {
        "code": "task_timer:resume",
        "module": "taskTimer",
        "action": "resume",
        "title": "resume task timer",
        "description": "permission for resume task timer",
    },
    {
        "code": "task_timer:stop",
        "module": "taskTimer",
        "action": "stop",
        "title": "stop task timer",
        "description": "permission for stop task timer",
    },
    {
        "code": "task_timer:delete",
        "module": "taskTimer",
        "action": "delete",
        "title": "delete task timer",
        "description": "permission for delete task timer",
    },

]
