PERMISSIONS = [
    # users
    {
        "code": "user:create",
        "module": "user",
        "action": "create",
        "title": "create user",
        "description": "Permission for creating a user",
    },
    {
        "code": "user:read",
        "module": "user",
        "action": "read",
        "title": "read user",
        "description": "permission for See the user data",
    },
    {
        "code": "user:update",
        "module": "user",
        "action": "update",
        "title": "update user",
        "description": "permission for update user data",
    },
    {
        "code": "user:delete",
        "module": "user",
        "action": "delete",
        "title": "delete user",
        "description": "permission for delete user data",
    },
    # ROLES
    {
        "code": "role:create",
        "module": "role",
        "action": "create",
        "title": "create role",
        "description": "Permission for creating a role",
    },
    {
        "code": "role:read",
        "module": "role",
        "action": "read",
        "title": "read role",
        "description": "Permission for read a role",
    },
    {
        "code": "role:update",
        "module": "role",
        "action": "update",
        "title": "update role",
        "description": "Permission for update a role",
    },
    {
        "code": "role:delete",
        "module": "role",
        "action": "delete",
        "title": "delete role",
        "description": "Permission for delete a role",
    },
    # ENQUIRY
    {
        "code": "enquiry:create",
        "module": "enquiry",
        "action": "create",
        "title": "create enquiry",
        "description": "permission for create enquiry data",
    },
    {
        "code": "enquiry:read",
        "module": "enquiry",
        "action": "read",
        "title": "read enquiry",
        "description": "permission for read enquiry data",
    },
    {
        "code": "enquiry:update",
        "module": "enquiry",
        "action": "update",
        "title": "update enquiry",
        "description": "permission for update enquiry data",
    },
    {
        "code": "enquiry:delete",
        "module": "enquiry",
        "action": "delete",
        "title": "delete enquiry",
        "description": "permission for delete enquiry data",
    },
    {
        "code": "lead:create",
        "module": "lead",
        "action": "create",
        "title": "create lead",
        "description": "permission for create lead data",
    },
    {
        "code": "lead:read",
        "module": "lead",
        "action": "read",
        "title": "read lead",
        "description": "permission for read lead data",
    },
    {
        "code": "lead:update",
        "module": "lead",
        "action": "update",
        "title": "update lead",
        "description": "permission for update lead data",
    },
    {
        "code": "lead:delete",
        "module": "lead",
        "action": "delete",
        "title": "delete lead",
        "description": "permission for delete lead data",
    },
    {
        "code": "team:create",
        "module": "team",
        "action": "create",
        "title": "create team",
        "description": "permission for create team data",
    },
    {
        "code": "team:read",
        "module": "team",
        "action": "read",
        "title": "read team",
        "description": "permission for read team data",
    },
    {
        "code": "team:update",
        "module": "team",
        "action": "update",
        "title": "update team",
        "description": "permission for update team data",
    },
    {
        "code": "team:delete",
        "module": "team",
        "action": "delete",
        "title": "delete team",
        "description": "permission for delete team data",
    },
    {
        "code": "team_cat:create",
        "module": "team_cat",
        "action": "create",
        "title": "create team category",
        "description": "permission for create team category data",
    },
    {
        "code": "team_cat:read",
        "module": "team_cat",
        "action": "read",
        "title": "read team category",
        "description": "permission for read team category data",
    },
    {
        "code": "team_cat:update",
        "module": "team_cat",
        "action": "update",
        "title": "update team category",
        "description": "permission for update team category data",
    },
    {
        "code": "team_cat:delete",
        "module": "team_cat",
        "action": "delete",
        "title": "delete team category",
        "description": "permission for delete team category data",
    },
    {
        "code": "deal:create",
        "module": "deal",
        "action": "create",
        "title": "create deal",
        "description": "permission for create deal data",
    },
    {
        "code": "deal:read",
        "module": "deal",
        "action": "read",
        "title": "read deal",
        "description": "permission for read deal data",
    },
    {
        "code": "deal:update",
        "module": "deal",
        "action": "update",
        "title": "update deal",
        "description": "permission for update deal data",
    },
    {
        "code": "deal:delete",
        "module": "deal",
        "action": "delete",
        "title": "delete deal",
        "description": "permission for delete deal data",
    },
    {
        "code": "quote:create",
        "module": "quote",
        "action": "create",
        "title": "create quote",
        "description": "permission for create quote data",
    },
    {
        "code": "quote:read",
        "module": "quote",
        "action": "read",
        "title": "read quote",
        "description": "permission for read quote data",
    },
    {
        "code": "quote:update",
        "module": "quote",
        "action": "update",
        "title": "update quote",
        "description": "permission for update quote data",
    },
    {
        "code": "quote:delete",
        "module": "quote",
        "action": "delete",
        "title": "delete quote",
        "description": "permission for delete quote data",
    },
    {
        "code": "event:create",
        "module": "event",
        "action": "create",
        "title": "create event",
        "description": "permission for create event data",
    },
    {
        "code": "event:read",
        "module": "event",
        "action": "read",
        "title": "read event",
        "description": "permission for read event data",
    },
    {
        "code": "event:update",
        "module": "event",
        "action": "update",
        "title": "update event",
        "description": "permission for update event data",
    },
    {
        "code": "event:delete",
        "module": "event",
        "action": "delete",
        "title": "delete event",
        "description": "permission for delete event data",
    },
    {
        "code": "event:create",
        "module": "event",
        "action": "create",
        "title": "create event",
        "description": "permission for create event data",
    },
    {
        "code": "invoice:read",
        "module": "invoice",
        "action": "read",
        "title": "read invoice",
        "description": "permission for read invoice data",
    },
    {
        "code": "invoice:update",
        "module": "invoice",
        "action": "update",
        "title": "update invoice",
        "description": "permission for update invoice data (allowed fields only)",
    },
    {
        "code": "invoice:delete",
        "module": "invoice",
        "action": "delete",
        "title": "delete invoice",
        "description": "permission for delete or void invoice",
    },
    {
        "code": "invoice:send",
        "module": "invoice",
        "action": "send",
        "title": "send invoice",
        "description": "permission for send invoice to client",
    },
    {
        "code": "invoice:download",
        "module": "invoice",
        "action": "download",
        "title": "download invoice",
        "description": "permission for download invoice PDF",
    },
    {
        "code": "invoice:mark-paid",
        "module": "invoice",
        "action": "mark-paid",
        "title": "mark invoice as paid",
        "description": "permission for mark invoice payment status as paid",
    },
    {
    "code": "invoice:cancel",
    "module": "invoice",
    "action": "cancel",
    "title": "cancel invoice",
    "description": "permission for cancel invoice without deleting it"
},
{
        "code": "note:create",
        "module": "note",
        "action": "create",
        "title": "create note",
        "description": "permission for create note data",
    },
    {
        "code": "note:read",
        "module": "note",
        "action": "read",
        "title": "read note",
        "description": "permission for read note data",
    },
    {
        "code": "note:update",
        "module": "note",
        "action": "update",
        "title": "update note",
        "description": "permission for update note data",
    },
    {
        "code": "note:delete",
        "module": "note",
        "action": "delete",
        "title": "delete note",
        "description": "permission for delete note data",
    },
]
