import type { Metadata } from "next";

import "../../app/globals.css";
import SideBar from "@/src/components/layouts/SideBar";
import NavBar from "@/src/components/layouts/NavBar";
import { MARGIN_TOP, SIDEBAR_WIDTH } from "@/src/constants/constants";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`ml-[${SIDEBAR_WIDTH}] mt-${MARGIN_TOP} p-6 bg-stone-50`}
      >

        <SideBar/>
        <NavBar/>
        {children}
        
      </body>
    </html>
  );
}